/*
 * Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
 *
 * WSO2 Inc. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.carbon.identity.remotefetch.common;

import java.io.File;
import java.util.Date;

/**
 * Holds details on Deployment Revisions.
 * Used to represent logical Revision data row at runtime.
 */
public class DeploymentRevision {

    private String fileRevisionId;
    private String configId;
    private File file;
    private String fileHash;
    private Date deployedDate;
    private DeploymentStatus deploymentStatus;
    private String itemName;
    private String errorMessage;
    private Date lastSynchronizedDate;

    /**
     * Status pf Deployment.
     */
    public enum DeploymentStatus {

        SUCCESS, FAIL, FILE_MISSING
    }

    /**
     * Default constructor.
     *
     * @param configId represents remoteFetchConfigurationId of the corresponding remote fetch configuration.
     *                 {@link RemoteFetchConfiguration}
     * @param file     represents local repo file.
     */
    public DeploymentRevision(String configId, File file) {

        this.configId = configId;
        this.file = file;
    }

    /**
     * Get file revision id.
     * Unique id for deployment revisions and generated by auto increment while adding into db.
     *
     * @return fileRevisionId
     */
    public String getDeploymentRevisionId() {

        return fileRevisionId;
    }

    /**
     * Set file revision id.
     *
     * @param fileRevisionId fileRevisionId
     */
    public void setDeploymentRevisionId(String fileRevisionId) {

        this.fileRevisionId = fileRevisionId;
    }

    /**
     * Get config Id.
     *
     * @return configId
     */
    public String getConfigId() {

        return configId;
    }

    /**
     * Set configId.
     *
     * @param configId configId
     */
    public void setConfigId(String configId) {

        this.configId = configId;
    }

    /**
     * Get File.
     *
     * @return file
     */
    public File getFile() {

        return file;
    }

    /**
     * Set file.
     *
     * @param file file.
     */
    public void setFile(File file) {

        this.file = file;
    }

    /**
     * Get FileHash which represents hash of the file used to check revision changed or not before deploying the file.
     *
     * @return fileHash
     */
    public String getFileHash() {

        return fileHash;
    }

    /**
     * Set fileHash.
     *
     * @param fileHash fileHash
     */
    public void setFileHash(String fileHash) {

        this.fileHash = fileHash;
    }

    /**
     * Get deployedDate which represent the time stamp of deployed time.
     *
     * @return deployedDate
     */
    public Date getDeployedDate() {

        if (deployedDate == null) {
            return null;
        } else {
            return new Date(deployedDate.getTime());
        }
    }

    /**
     * Set deployeddate.
     *
     * @param deployedDate deployedDate
     */
    public void setDeployedDate(Date deployedDate) {

        if (deployedDate == null) {
            this.deployedDate = null;
        } else {
            this.deployedDate = new Date(deployedDate.getTime());
        }
    }

    /**
     * Get synced Date to  represent last synced Time.
     *
     * @return synced Date.
     */
    public Date getLastSynchronizedDate() {

        if (lastSynchronizedDate == null) {
            return null;
        } else {
            return new Date(lastSynchronizedDate.getTime());
        }
    }

    /**
     * Set syncedDate.
     *
     * @param lastSynchronizedDate syncedDate.
     */
    public void setLastSynchronizedDate(Date lastSynchronizedDate) {

        if (lastSynchronizedDate == null) {
            this.lastSynchronizedDate = null;
        } else {
            this.lastSynchronizedDate = new Date(lastSynchronizedDate.getTime());
        }
    }

    /**
     * Get deploymentStatus whether deployment failed or not.
     *
     * @return deploymentStatus
     */
    public DeploymentStatus getDeploymentStatus() {

        return deploymentStatus;
    }

    /**
     * Set deploymentStatus.
     *
     * @param deploymentStatus deploymentStatus
     */
    public void setDeploymentStatus(DeploymentStatus deploymentStatus) {

        this.deploymentStatus = deploymentStatus;
    }

    /**
     * Get ItemName which represents artifact name eg : ServiceProvider name.
     *
     * @return itemName
     */
    public String getItemName() {

        return itemName;
    }

    /**
     * Set itemName.
     *
     * @param itemName itemName.
     */
    public void setItemName(String itemName) {

        this.itemName = itemName;
    }

    public String getErrorMessage() {

        return errorMessage;
    }

    public void setErrorMessage(String errorMessage) {

        this.errorMessage = errorMessage;
    }
}
